Lession09/Controllers/LvsCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lession09.Models;

namespace Lession09.Controllers
{
    public class LvsCategoriesController : Controller
    {
        private readonly LvsBookStoreContext _context;

        public LvsCategoriesController(LvsBookStoreContext context)
        {
            _context = context;
        }

        // GET: LvsCategories
        public async Task<IActionResult> LvsIndex()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: LvsCategories/LvsDetails/5
        public async Task<IActionResult> LvsDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: LvsCategories/LvsCreate
        public IActionResult LvsCreate()
        {
            return View();
        }

        // POST: LvsCategories/LvsCreate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LvsCreate([Bind("CategoryId,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(LvsIndex));
            }
            return View(category);
        }

        // GET: LvsCategories/LvsEdit/5
        public async Task<IActionResult> LvsEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: LvsCategories/LvsEdit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LvsEdit(int id, [Bind("CategoryId,CategoryName")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LvsCategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(LvsIndex));
            }
            return View(category);
        }

        // GET: LvsCategories/LvsDelete/5
        public async Task<IActionResult> LvsDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: LvsCategories/LvsDelete/5
        [HttpPost, ActionName("LvsDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LvsDeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(LvsIndex));
        }

        private bool LvsCategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

Lession09/Controllers/LvsHomeController.cs
using System.Diagnostics;
using Lesssion09.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lesssion09.Controllers
{
    public class LvsHomeController : Controller
    {
        private readonly ILogger<LvsHomeController> _logger;

        public LvsHomeController(ILogger<LvsHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult LvsIndex()
        {
            return View();
        }

        public IActionResult LvsAbout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lession09/Controllers/LvsPublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lession09.Models;

namespace Lession09.Controllers
{
    public class LvsPublishersController : Controller
    {
        private readonly LvsBookStoreContext _context;

        public LvsPublishersController(LvsBookStoreContext context)
        {
            _context = context;
        }

        // GET: LvsPublishers
        public async Task<IActionResult> LvsIndex()
        {
            return View(await _context.Publishers.ToListAsync());
        }

        // GET: LvsPublishers/LvsDetails/5
        public async Task<IActionResult> LvsDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.PublisherId == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: LvsPublishers/LvsCreate
        public IActionResult LvsCreate()
        {
            return View();
        }

        // POST: LvsPublishers/LvsCreate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LvsCreate([Bind("PublisherId,PublisherName,Phone,Address")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(publisher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(LvsIndex));
            }
            return View(publisher);
        }

        // GET: LvsPublishers/LvsEdit/5
        public async Task<IActionResult> LvsEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers.FindAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: LvsPublishers/LvsEdit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LvsEdit(int id, [Bind("PublisherId,PublisherName,Phone,Address")] Publisher publisher)
        {
            if (id != publisher.PublisherId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publisher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LvsPublisherExists(publisher.PublisherId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(LvsIndex));
            }
            return View(publisher);
        }

        // GET: LvsPublishers/LvsDelete/5
        public async Task<IActionResult> LvsDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.PublisherId == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: LvsPublishers/LvsDelete/5
        [HttpPost, ActionName("LvsDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LvsDeleteConfirmed(int id)
        {
            var publisher = await _context.Publishers.FindAsync(id);
            if (publisher != null)
            {
                _context.Publishers.Remove(publisher);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(LvsIndex));
        }

        private bool LvsPublisherExists(int id)
        {
            return _context.Publishers.Any(e => e.PublisherId == id);
        }
    }
}

Lession09/Views/Shared/_LvsLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesssion09</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesssion09.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <Partial name="_LvsNavbar"/>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Lesssion09 - <a asp-area="" asp-controller="LvsHome" asp-action="LvsAbout">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Lession09/Views/Shared/_LvsNavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="LvsHome" asp-action="LvsIndex">Lession09</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="LvsHome" asp-action="LvsIndex">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="LvsHome" asp-action="LvsAbout">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="LvsCategories" asp-action="LvsIndex">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="LvsPublishers" asp-action="LvsIndex">LvsPublishers</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>